<?php

    $clg_data=[
        [
            'id'=>'id1',
            'name'=>'clg1'
        ],
       [
            'id'=>'id2',
            'name'=>'clg2'
        ],
        [
            'id'=>'id3',
            'name'=>'clg3'
        ],
        [
            'id'=>'id4',
            'name'=>'clg4'
        ],
        [
            'id'=>'id5',
            'name'=>'clg5'
        ]
    ];
    $doc_data=[
       [
            'name'=>'doc1',
            'type'=>'A',
            'college'=>'id1',
            'status'=>0
        ],
        [
            'name'=>'doc2',
            'type'=>'B',
            'college'=>'id2',
            'status'=>1
        ],
       [
            'name'=>'doc3',
            'type'=>'C',
            'college'=>'id3',
            'status'=>1
        ],
        [
            'name'=>'doc4',
            'type'=>'D',
            'college'=>'id4',
            'status'=>0
        ],
       [
            'name'=>'doc5',
            'type'=>'E',
            'college'=>'id5',
            'status'=>1
        ],
    ];
?>
